// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class AccountConfiguration : IEntityTypeConfiguration<Account>
    {
        public void Configure(EntityTypeBuilder<Account> entity)
        {
            entity.HasKey(e => e.Username)
                .HasName("PK__Account__536C85E5964FC363");

            entity.HasOne(d => d.AccountCategory)
                .WithMany(p => p.Account)
                .HasForeignKey(d => d.AccountCategoryID)
                .HasConstraintName("FK_Account_AccountCategory");
        }
    }
}
