// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace vuonsendaMVC.Models
{
    public partial class ArticleCategory
    {
        public ArticleCategory()
        {
            Article = new HashSet<Article>();
        }

        [Key]
        public int ArticleCategoryID { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(200)]
        public string Title { get; set; }
        [StringLength(4000)]
        public string Dercription { get; set; }
        [StringLength(255)]
        public string Avatar { get; set; }
        [StringLength(255)]
        public string Thumb { get; set; }
        public bool? Status { get; set; }
        public int? Position { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [StringLength(50)]
        public string CreateBy { get; set; }
        public int? ArticleMainCategoryID { get; set; }
        [StringLength(50)]
        public string UpdateBy { get; set; }

        [ForeignKey(nameof(ArticleMainCategoryID))]
        [InverseProperty("ArticleCategory")]
        public virtual ArticleMainCategory ArticleMainCategory { get; set; }
        [ForeignKey(nameof(CreateBy))]
        [InverseProperty(nameof(Account.ArticleCategory))]
        public virtual Account CreateByNavigation { get; set; }
        [InverseProperty("ArticleCategory")]
        public virtual ICollection<Article> Article { get; set; }
    }
}