// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class ClientConfiguration : IEntityTypeConfiguration<Client>
    {
        public void Configure(EntityTypeBuilder<Client> entity)
        {
            entity.HasOne(d => d.ApproveByNavigation)
                .WithMany(p => p.Client)
                .HasForeignKey(d => d.ApproveBy)
                .HasConstraintName("FK_Client_Account");

            entity.HasOne(d => d.ClientCategory)
                .WithMany(p => p.Client)
                .HasForeignKey(d => d.ClientCategoryID)
                .HasConstraintName("FK_Client_ClientCategory");
        }
    }
}
