// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class ClientCategoryConfiguration : IEntityTypeConfiguration<ClientCategory>
    {
        public void Configure(EntityTypeBuilder<ClientCategory> entity)
        {
            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.ClientCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ClientCategory_Account");
        }
    }
}
