// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class ContactConfiguration : IEntityTypeConfiguration<Contact>
    {
        public void Configure(EntityTypeBuilder<Contact> entity)
        {
            entity.HasOne(d => d.ApproveByNavigation)
                .WithMany(p => p.Contact)
                .HasForeignKey(d => d.ApproveBy)
                .HasConstraintName("FK_Contact_Account");

            entity.HasOne(d => d.ContactCategory)
                .WithMany(p => p.Contact)
                .HasForeignKey(d => d.ContactCategoryID)
                .HasConstraintName("FK_Contact_ContactCategory");
        }
    }
}
