// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class ContactCategoryConfiguration : IEntityTypeConfiguration<ContactCategory>
    {
        public void Configure(EntityTypeBuilder<ContactCategory> entity)
        {
            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.ContactCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ContactCategory_Account");
        }
    }
}
