// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class PictureConfiguration : IEntityTypeConfiguration<Picture>
    {
        public void Configure(EntityTypeBuilder<Picture> entity)
        {
            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.Picture)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_Picture_Account");

            entity.HasOne(d => d.PictureCategory)
                .WithMany(p => p.Picture)
                .HasForeignKey(d => d.PictureCategoryID)
                .HasConstraintName("FK_Picture_PictureCategory");
        }
    }
}
