// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class PictureMainCategoryConfiguration : IEntityTypeConfiguration<PictureMainCategory>
    {
        public void Configure(EntityTypeBuilder<PictureMainCategory> entity)
        {
            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.PictureMainCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_PictureMainCategory_Account");
        }
    }
}
