// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class ProductCategoryConfiguration : IEntityTypeConfiguration<ProductCategory>
    {
        public void Configure(EntityTypeBuilder<ProductCategory> entity)
        {
            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.ProductCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ProductCategory_Account");

            entity.HasOne(d => d.ProductMainCategory)
                .WithMany(p => p.ProductCategory)
                .HasForeignKey(d => d.ProductMainCategoryID)
                .HasConstraintName("FK_ProductCategory_ProductMainCategory");
        }
    }
}
