// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace vuonsendaMVC.Models
{
    public class TB_ThongKeConfiguration : IEntityTypeConfiguration<TB_ThongKe>
    {
        public void Configure(EntityTypeBuilder<TB_ThongKe> entity)
        {
            entity.HasKey(e => e.MaTB)
                .HasName("PK__TB_Thong__2725006FC4CBFD00");
        }
    }
}
