// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace vuonsendaMVC.Models
{
    public partial class TB_ThongKe
    {
        [Key]
        public int MaTB { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ThoiGian { get; set; }
        public long SoTruyCap { get; set; }
    }
}