// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TauThuyenViet.Models
{
    public class AccountCategoryConfiguration : IEntityTypeConfiguration<AccountCategory>
    {
        public void Configure(EntityTypeBuilder<AccountCategory> entity)
        {
            entity.HasKey(e => e.AccountCategoryID)
                .HasName("PK_ACCOUNTTYPE")
                .IsClustered(false);
        }
    }
}
