// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TauThuyenViet.Models
{
    public class ArticleMainCategoryConfiguration : IEntityTypeConfiguration<ArticleMainCategory>
    {
        public void Configure(EntityTypeBuilder<ArticleMainCategory> entity)
        {
            entity.HasKey(e => e.ArticleMainCategoryID)
                .HasName("PK_ARTICLEMAINCATEGORY")
                .IsClustered(false);

            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.ArticleMainCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ARTICLEM_ACCOUNT_A_ACCOUNT");
        }
    }
}
