// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TauThuyenViet.Models
{
    public class ArticleCategoryConfiguration : IEntityTypeConfiguration<ArticleCategory>
    {
        public void Configure(EntityTypeBuilder<ArticleCategory> entity)
        {
            entity.HasKey(e => e.ArticleCategoryID)
                .HasName("PK_ARTICLECATEGORY")
                .IsClustered(false);

            entity.HasOne(d => d.ArticleMainCategory)
                .WithMany(p => p.ArticleCategory)
                .HasForeignKey(d => d.ArticleMainCategoryID)
                .HasConstraintName("FK_ARTICLEC_ARTICLEMA_ARTICLEM");

            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.ArticleCategory)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ARTICLEC_ACCOUNT_A_ACCOUNT");
        }
    }
}
