// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TauThuyenViet.Models
{
    public class ArticleConfiguration : IEntityTypeConfiguration<Article>
    {
        public void Configure(EntityTypeBuilder<Article> entity)
        {
            entity.HasKey(e => e.ArticleID)
                .HasName("PK_ARTICLE")
                .IsClustered(false);

            entity.HasOne(d => d.ArticleCategory)
                .WithMany(p => p.Article)
                .HasForeignKey(d => d.ArticleCategoryID)
                .HasConstraintName("FK_ARTICLE_ARTICLECA_ARTICLEC");

            entity.HasOne(d => d.CreateByNavigation)
                .WithMany(p => p.Article)
                .HasForeignKey(d => d.CreateBy)
                .HasConstraintName("FK_ARTICLE_ACCOUNT_A_ACCOUNT");
        }
    }
}
